---
- name: Install expect
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - expect 
    - expect-devel 
#   - "{{ expects }}"
  tags:
    - expecttesting
