# docker-compose.yml
version: '3'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pgtestuser
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: test_db
    volumes:
      - db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
    pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
# postgresql13:
#   image: "postgres" # use latest official postgres version
#   env_file:
#     - postgresql.env # configure postgres
#   volumes:
#     - db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
#   ports:
#     - 5432:5432

  sqlserver-db:
    container_name: sqlserver-db
#   image: microsoft/mssql-server-linux:2017-latest
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    env_file:
      - mssql.env
#   environment:
#     SA_PASSWORD: "Testing123"
#     ACCEPT_EULA: "Y"
#     MSSQL_BACKUP_DIR="/var/opt/sqlserver"
#     MSSQL_DATA_DIR="/var/opt/sqlserver"
#     MSSQL_LOG_DIR="/var/opt/sqlserver"
    volumes:
      - systemdbs:/var/opt/mssql
      - userdbs:/var/opt/sqlserver
    ports:
      - "15789:1433"
volumes:
  db-data: # named volumes can be managed easier using docker-compose
  systemdbs:
  userdbs:
